spring.application.name=analytics-service
server.port=8090

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/event_management_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:your_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ALL Service URLs for OpenFeign
event.service.url=${EVENT_SERVICE_URL:http://localhost:8081}
ticketing.service.url=${TICKETING_SERVICE_URL:http://localhost:8082}
booking.service.url=${BOOKING_SERVICE_URL:http://localhost:8083}
payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8084}
attendee.service.url=${ATTENDEE_SERVICE_URL:http://localhost:8085}
review.service.url=${REVIEW_SERVICE_URL:http://localhost:8088}
vendor.service.url=${VENDOR_SERVICE_URL:http://localhost:8089}
